name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  test:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node-version: [10.x, 12.x, 14.x, 16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout branch
      uses: actions/checkout@v2

    - name: setup node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: npm ci

    - name: run tests
      run: npm test
